def foo()
    a = 100
    def closure(x)
        return a + x
    end
    return closure
end

c = foo()
write(c(4))
# write(c(200))

def ccc()
    write('ccc')
    #write(x1)
end
    
def xxx()
    write('xxx')
    x1 = 1
    return ccc()
end

xxx()

def yyy()
end