def foo()
    a = 100
    def closure(x)
        return a + x
    end
    return closure
end

#c = foo()
#write(c(4))
# write(c(200))

def ccc(x1,x2)
    write('ccc' + x1 + '\n')
    write('ccc' + x2 + '\n')
    write(x1+x2)
end
    
def xxx()
    write('xxx')
    x1 = 1
    return ccc(x1+1,1)
end

xxx()
