
a = [10,9,8,7,6,5,4,3,2,1]
sum = 0
for i,v in a
    sum += v
end

writeln(sum)

for i,v in 10
	sum += v
end

writeln(sum)

a = {1:2, 2:9, 3:10}

for i,v in a
	sum += v
end

writeln(sum)
